# Site settings
title: Can You DevOps With Windows? 
email: steven.murawski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # "powershell" # the subpath of your site, e.g. /blog/
url: "http://stevenmurawski.azurewebsites.net" # the base hostname & protocol for your site
twitter_username: stevenmurawski
github_username:  smurawski

# Build settings
markdown: kramdown
